name: Deploy to Firebase Hosting on merge

'on':
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    env:
      VITE_APP_API_KEY: '${{ secrets.VITE_APP_API_KEY }}'
      VITE_APP_AUTH_DOMAIN: '${{ secrets.VITE_APP_AUTH_DOMAIN }}'
      VITE_APP_DATABASE_URL: '${{ secrets.VITE_APP_DATABASE_URL }}'
      VITE_APP_PROJECT_ID: '${{ secrets.VITE_APP_PROJECT_ID }}'
      VITE_APP_STORAGE_BUCKET: '${{ secrets.VITE_APP_STORAGE_BUCKET }}'
      VITE_APP_MESSAGING_SENDER_ID: '${{ secrets.VITE_APP_MESSAGING_SENDER_ID }}'
      VITE_APP_APP_ID: '${{ secrets.VITE_APP_APP_ID }}'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build application
        run: npm run build

      - name: Deploy to firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_CLOUDY_9121A }}'
          channelId: live
          projectId: cloudy-9121a
